/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedUntangleRouteImport } from './routes/_authenticated/untangle'
import { Route as AuthenticatedStatesRouteImport } from './routes/_authenticated/states'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as AuthenticatedMeaningRouteImport } from './routes/_authenticated/meaning'
import { Route as AuthenticatedEditorialRouteImport } from './routes/_authenticated/editorial'
import { Route as AuthenticatedDumpRouteImport } from './routes/_authenticated/dump'
import { Route as AuthenticatedCourtroomRouteImport } from './routes/_authenticated/courtroom'
import { Route as AuthenticatedClockRouteImport } from './routes/_authenticated/clock'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUntangleRoute = AuthenticatedUntangleRouteImport.update({
  id: '/untangle',
  path: '/untangle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatesRoute = AuthenticatedStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeaningRoute = AuthenticatedMeaningRouteImport.update({
  id: '/meaning',
  path: '/meaning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorialRoute = AuthenticatedEditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDumpRoute = AuthenticatedDumpRouteImport.update({
  id: '/dump',
  path: '/dump',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCourtroomRoute = AuthenticatedCourtroomRouteImport.update({
  id: '/courtroom',
  path: '/courtroom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClockRoute = AuthenticatedClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/clock': typeof AuthenticatedClockRoute
  '/courtroom': typeof AuthenticatedCourtroomRoute
  '/dump': typeof AuthenticatedDumpRoute
  '/editorial': typeof AuthenticatedEditorialRoute
  '/meaning': typeof AuthenticatedMeaningRoute
  '/start': typeof AuthenticatedStartRoute
  '/states': typeof AuthenticatedStatesRoute
  '/untangle': typeof AuthenticatedUntangleRoute
  '/vault': typeof AuthenticatedVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/clock': typeof AuthenticatedClockRoute
  '/courtroom': typeof AuthenticatedCourtroomRoute
  '/dump': typeof AuthenticatedDumpRoute
  '/editorial': typeof AuthenticatedEditorialRoute
  '/meaning': typeof AuthenticatedMeaningRoute
  '/start': typeof AuthenticatedStartRoute
  '/states': typeof AuthenticatedStatesRoute
  '/untangle': typeof AuthenticatedUntangleRoute
  '/vault': typeof AuthenticatedVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/clock': typeof AuthenticatedClockRoute
  '/_authenticated/courtroom': typeof AuthenticatedCourtroomRoute
  '/_authenticated/dump': typeof AuthenticatedDumpRoute
  '/_authenticated/editorial': typeof AuthenticatedEditorialRoute
  '/_authenticated/meaning': typeof AuthenticatedMeaningRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/_authenticated/states': typeof AuthenticatedStatesRoute
  '/_authenticated/untangle': typeof AuthenticatedUntangleRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/clock'
    | '/courtroom'
    | '/dump'
    | '/editorial'
    | '/meaning'
    | '/start'
    | '/states'
    | '/untangle'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/about'
    | '/clock'
    | '/courtroom'
    | '/dump'
    | '/editorial'
    | '/meaning'
    | '/start'
    | '/states'
    | '/untangle'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/about'
    | '/_authenticated/clock'
    | '/_authenticated/courtroom'
    | '/_authenticated/dump'
    | '/_authenticated/editorial'
    | '/_authenticated/meaning'
    | '/_authenticated/start'
    | '/_authenticated/states'
    | '/_authenticated/untangle'
    | '/_authenticated/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/untangle': {
      id: '/_authenticated/untangle'
      path: '/untangle'
      fullPath: '/untangle'
      preLoaderRoute: typeof AuthenticatedUntangleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/states': {
      id: '/_authenticated/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof AuthenticatedStatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meaning': {
      id: '/_authenticated/meaning'
      path: '/meaning'
      fullPath: '/meaning'
      preLoaderRoute: typeof AuthenticatedMeaningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editorial': {
      id: '/_authenticated/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof AuthenticatedEditorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dump': {
      id: '/_authenticated/dump'
      path: '/dump'
      fullPath: '/dump'
      preLoaderRoute: typeof AuthenticatedDumpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courtroom': {
      id: '/_authenticated/courtroom'
      path: '/courtroom'
      fullPath: '/courtroom'
      preLoaderRoute: typeof AuthenticatedCourtroomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clock': {
      id: '/_authenticated/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof AuthenticatedClockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedClockRoute: typeof AuthenticatedClockRoute
  AuthenticatedCourtroomRoute: typeof AuthenticatedCourtroomRoute
  AuthenticatedDumpRoute: typeof AuthenticatedDumpRoute
  AuthenticatedEditorialRoute: typeof AuthenticatedEditorialRoute
  AuthenticatedMeaningRoute: typeof AuthenticatedMeaningRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
  AuthenticatedStatesRoute: typeof AuthenticatedStatesRoute
  AuthenticatedUntangleRoute: typeof AuthenticatedUntangleRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedClockRoute: AuthenticatedClockRoute,
  AuthenticatedCourtroomRoute: AuthenticatedCourtroomRoute,
  AuthenticatedDumpRoute: AuthenticatedDumpRoute,
  AuthenticatedEditorialRoute: AuthenticatedEditorialRoute,
  AuthenticatedMeaningRoute: AuthenticatedMeaningRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
  AuthenticatedStatesRoute: AuthenticatedStatesRoute,
  AuthenticatedUntangleRoute: AuthenticatedUntangleRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
