/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhiteboardRouteImport } from './routes/_authenticated/whiteboard'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedUntangleRouteImport } from './routes/_authenticated/untangle'
import { Route as AuthenticatedStatesRouteImport } from './routes/_authenticated/states'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as AuthenticatedMeaningRouteImport } from './routes/_authenticated/meaning'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedEssaysRouteImport } from './routes/_authenticated/essays'
import { Route as AuthenticatedEditorialRouteImport } from './routes/_authenticated/editorial'
import { Route as AuthenticatedDumpRouteImport } from './routes/_authenticated/dump'
import { Route as AuthenticatedCourtroomRouteImport } from './routes/_authenticated/courtroom'
import { Route as AuthenticatedColophonRouteImport } from './routes/_authenticated/colophon'
import { Route as AuthenticatedClockRouteImport } from './routes/_authenticated/clock'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhiteboardRoute = AuthenticatedWhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUntangleRoute = AuthenticatedUntangleRouteImport.update({
  id: '/untangle',
  path: '/untangle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatesRoute = AuthenticatedStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeaningRoute = AuthenticatedMeaningRouteImport.update({
  id: '/meaning',
  path: '/meaning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEssaysRoute = AuthenticatedEssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorialRoute = AuthenticatedEditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDumpRoute = AuthenticatedDumpRouteImport.update({
  id: '/dump',
  path: '/dump',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCourtroomRoute = AuthenticatedCourtroomRouteImport.update({
  id: '/courtroom',
  path: '/courtroom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedColophonRoute = AuthenticatedColophonRouteImport.update({
  id: '/colophon',
  path: '/colophon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClockRoute = AuthenticatedClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AuthenticatedAboutRoute
  '/clock': typeof AuthenticatedClockRoute
  '/colophon': typeof AuthenticatedColophonRoute
  '/courtroom': typeof AuthenticatedCourtroomRoute
  '/dump': typeof AuthenticatedDumpRoute
  '/editorial': typeof AuthenticatedEditorialRoute
  '/essays': typeof AuthenticatedEssaysRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/meaning': typeof AuthenticatedMeaningRoute
  '/start': typeof AuthenticatedStartRoute
  '/states': typeof AuthenticatedStatesRoute
  '/untangle': typeof AuthenticatedUntangleRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/whiteboard': typeof AuthenticatedWhiteboardRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AuthenticatedAboutRoute
  '/clock': typeof AuthenticatedClockRoute
  '/colophon': typeof AuthenticatedColophonRoute
  '/courtroom': typeof AuthenticatedCourtroomRoute
  '/dump': typeof AuthenticatedDumpRoute
  '/editorial': typeof AuthenticatedEditorialRoute
  '/essays': typeof AuthenticatedEssaysRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/meaning': typeof AuthenticatedMeaningRoute
  '/start': typeof AuthenticatedStartRoute
  '/states': typeof AuthenticatedStatesRoute
  '/untangle': typeof AuthenticatedUntangleRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/whiteboard': typeof AuthenticatedWhiteboardRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/clock': typeof AuthenticatedClockRoute
  '/_authenticated/colophon': typeof AuthenticatedColophonRoute
  '/_authenticated/courtroom': typeof AuthenticatedCourtroomRoute
  '/_authenticated/dump': typeof AuthenticatedDumpRoute
  '/_authenticated/editorial': typeof AuthenticatedEditorialRoute
  '/_authenticated/essays': typeof AuthenticatedEssaysRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/meaning': typeof AuthenticatedMeaningRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/_authenticated/states': typeof AuthenticatedStatesRoute
  '/_authenticated/untangle': typeof AuthenticatedUntangleRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/whiteboard': typeof AuthenticatedWhiteboardRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/about'
    | '/clock'
    | '/colophon'
    | '/courtroom'
    | '/dump'
    | '/editorial'
    | '/essays'
    | '/library'
    | '/meaning'
    | '/start'
    | '/states'
    | '/untangle'
    | '/vault'
    | '/whiteboard'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/about'
    | '/clock'
    | '/colophon'
    | '/courtroom'
    | '/dump'
    | '/editorial'
    | '/essays'
    | '/library'
    | '/meaning'
    | '/start'
    | '/states'
    | '/untangle'
    | '/vault'
    | '/whiteboard'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/about'
    | '/_authenticated/clock'
    | '/_authenticated/colophon'
    | '/_authenticated/courtroom'
    | '/_authenticated/dump'
    | '/_authenticated/editorial'
    | '/_authenticated/essays'
    | '/_authenticated/library'
    | '/_authenticated/meaning'
    | '/_authenticated/start'
    | '/_authenticated/states'
    | '/_authenticated/untangle'
    | '/_authenticated/vault'
    | '/_authenticated/whiteboard'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whiteboard': {
      id: '/_authenticated/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof AuthenticatedWhiteboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/untangle': {
      id: '/_authenticated/untangle'
      path: '/untangle'
      fullPath: '/untangle'
      preLoaderRoute: typeof AuthenticatedUntangleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/states': {
      id: '/_authenticated/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof AuthenticatedStatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meaning': {
      id: '/_authenticated/meaning'
      path: '/meaning'
      fullPath: '/meaning'
      preLoaderRoute: typeof AuthenticatedMeaningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/essays': {
      id: '/_authenticated/essays'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof AuthenticatedEssaysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editorial': {
      id: '/_authenticated/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof AuthenticatedEditorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dump': {
      id: '/_authenticated/dump'
      path: '/dump'
      fullPath: '/dump'
      preLoaderRoute: typeof AuthenticatedDumpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courtroom': {
      id: '/_authenticated/courtroom'
      path: '/courtroom'
      fullPath: '/courtroom'
      preLoaderRoute: typeof AuthenticatedCourtroomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colophon': {
      id: '/_authenticated/colophon'
      path: '/colophon'
      fullPath: '/colophon'
      preLoaderRoute: typeof AuthenticatedColophonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clock': {
      id: '/_authenticated/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof AuthenticatedClockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedClockRoute: typeof AuthenticatedClockRoute
  AuthenticatedColophonRoute: typeof AuthenticatedColophonRoute
  AuthenticatedCourtroomRoute: typeof AuthenticatedCourtroomRoute
  AuthenticatedDumpRoute: typeof AuthenticatedDumpRoute
  AuthenticatedEditorialRoute: typeof AuthenticatedEditorialRoute
  AuthenticatedEssaysRoute: typeof AuthenticatedEssaysRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMeaningRoute: typeof AuthenticatedMeaningRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
  AuthenticatedStatesRoute: typeof AuthenticatedStatesRoute
  AuthenticatedUntangleRoute: typeof AuthenticatedUntangleRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWhiteboardRoute: typeof AuthenticatedWhiteboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedClockRoute: AuthenticatedClockRoute,
  AuthenticatedColophonRoute: AuthenticatedColophonRoute,
  AuthenticatedCourtroomRoute: AuthenticatedCourtroomRoute,
  AuthenticatedDumpRoute: AuthenticatedDumpRoute,
  AuthenticatedEditorialRoute: AuthenticatedEditorialRoute,
  AuthenticatedEssaysRoute: AuthenticatedEssaysRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMeaningRoute: AuthenticatedMeaningRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
  AuthenticatedStatesRoute: AuthenticatedStatesRoute,
  AuthenticatedUntangleRoute: AuthenticatedUntangleRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWhiteboardRoute: AuthenticatedWhiteboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
